/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cartridges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cartridges */
        get: operations["cartridges_api_cartridges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Solve */
        post: operations["post_solve_api_solve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/true": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post True
         * @description Fit a BC from observed drops — needs persistence (rifle/load profiles),
         *     which is out of scope for this build. See ARCHITECTURE.md's build order.
         *
         *     TODO: given a Shot and a list of (range_yd, observed_drop_in), bisect the
         *     BC until modelled drop matches observation in the least-squares sense. Two
         *     observations at different ranges are enough to be useful; one is not.
         *     Persist the fitted BC per rifle+load once profiles exist.
         */
        post: operations["post_true_api_true_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CartridgeOut
         * @description A preset. These are published figures, not measured on the user's rifle —
         *     the UI must say so, and truing must overwrite them.
         */
        CartridgeOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Calibre In */
            calibre_in: number;
            /** Length In */
            length_in: number;
            /** Weight Gr */
            weight_gr: number;
            /** Bc G7 */
            bc_g7: number;
            /** Bc G1 */
            bc_g1: number;
            /** Muzzle Fps */
            muzzle_fps: number;
            /** Twist In */
            twist_in: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * SampleOut
         * @description One point on the trajectory. Ranges/offsets are in the requested unit
         *     system so the chart layer never converts.
         */
        SampleOut: {
            /** Range */
            range: number;
            /** Drop */
            drop: number;
            /** Drift */
            drift: number;
            /** Drift Wind */
            drift_wind: number;
            /** Spin */
            spin: number;
            /** Velocity */
            velocity: number;
            /** Mach */
            mach: number;
            /** Energy */
            energy: number;
            /** Elevation */
            elevation: number;
            /** Windage */
            windage: number;
            /** Tof */
            tof: number;
        };
        /** ShotIn */
        ShotIn: {
            /** Calibre In */
            calibre_in: number;
            /** Length In */
            length_in: number;
            /** Weight Gr */
            weight_gr: number;
            /** Bc */
            bc: number;
            /**
             * Drag Model
             * @default G7
             * @enum {string}
             */
            drag_model: "G7" | "G1";
            /**
             * Muzzle Fps
             * @default 2600
             */
            muzzle_fps: number;
            /**
             * Muzzle Sd Fps
             * @default 0
             */
            muzzle_sd_fps: number;
            /**
             * Twist In
             * @default 11
             */
            twist_in: number;
            /**
             * Zero Yd
             * @default 100
             */
            zero_yd: number;
            /**
             * Sight Height In
             * @default 2.2
             */
            sight_height_in: number;
            /**
             * Temp F
             * @default 59
             */
            temp_f: number;
            /**
             * Humidity Pct
             * @default 50
             */
            humidity_pct: number;
            /**
             * Baro In Hg
             * @default 29.92
             */
            baro_in_hg: number;
            /**
             * Altitude Ft
             * @default 0
             */
            altitude_ft: number;
            /** Wind */
            wind?: components["schemas"]["WindZoneIn"][];
            /**
             * Target Yd
             * @default 1000
             */
            target_yd: number;
            /**
             * Look Angle Deg
             * @default 0
             */
            look_angle_deg: number;
            /**
             * Latitude Deg
             * @default 39
             */
            latitude_deg: number;
            /**
             * Azimuth Deg
             * @default 0
             */
            azimuth_deg: number;
            /**
             * Include Spin Drift
             * @default true
             */
            include_spin_drift: boolean;
            /**
             * Include Coriolis
             * @default true
             */
            include_coriolis: boolean;
            /**
             * Include Aero Jump
             * @default true
             */
            include_aero_jump: boolean;
            /**
             * Unit System
             * @default imperial
             * @enum {string}
             */
            unit_system: "imperial" | "metric";
            /**
             * Sample Step Yd
             * @default 100
             */
            sample_step_yd: number;
        };
        /** SolutionOut */
        SolutionOut: {
            /** Elevation */
            elevation: number;
            /** Windage */
            windage: number;
            /**
             * Windage Direction
             * @enum {string}
             */
            windage_direction: "LEFT" | "RIGHT";
            /**
             * Angular Unit
             * @enum {string}
             */
            angular_unit: "MOA" | "mil";
            /** Drop */
            drop: number;
            /** Drift */
            drift: number;
            /** Wind Deflection */
            wind_deflection: number;
            /** Spin Drift */
            spin_drift: number;
            /** Coriolis */
            coriolis: number;
            /** Max Ordinate */
            max_ordinate: number;
            /** Mv Spread */
            mv_spread: number;
            /**
             * Linear Unit
             * @enum {string}
             */
            linear_unit: "in" | "cm";
            /** Tof */
            tof: number;
            /** Velocity */
            velocity: number;
            /** Mach */
            mach: number;
            /** Energy */
            energy: number;
            /** Launch Angle Moa */
            launch_angle_moa: number;
            /** Sg */
            sg: number;
            /** Aero Jump */
            aero_jump: number;
            /** Air Density */
            air_density: number;
            /** Sound Speed */
            sound_speed: number;
            /** Reached Target */
            reached_target: boolean;
            /** Warnings */
            warnings?: string[];
            /** Trajectory */
            trajectory?: components["schemas"]["SampleOut"][];
            /** Range Card */
            range_card?: components["schemas"]["SampleOut"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WindZoneIn */
        WindZoneIn: {
            /**
             * Speed Mph
             * @default 0
             */
            speed_mph: number;
            /**
             * Clock
             * @description Direction wind comes FROM, clock hours
             * @default 3
             */
            clock: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    cartridges_api_cartridges_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CartridgeOut"][];
                };
            };
        };
    };
    post_solve_api_solve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShotIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolutionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_true_api_true_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
